language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install build-essential cmake git swig qt4-dev-tools python-dev python-pip libgdal1h libgdal-dev libgdal1-dev libqglviewer-dev-common libboost-system-dev libboost-graph-dev python-numpy python-scipy python-gdal python-matplotlib python-netcdf libgmp-dev libmpfr-dev libboost-all-dev
 - sudo pip install reimport
 - curl https://gforge.inria.fr/frs/download.php/33525/CGAL-4.4.tar.gz | tar zxv
 - cd CGAL-4.4
 - cmake . && make && sudo make install 
 - cd ..
 - wget https://github.com/Oslandia/SFCGAL/archive/v1.0.5.zip 
 - unzip v1.0.5.zip 
 - cd SFCGAL-1.0.5/
 - cmake . && make && sudo make install
 - cd ..

script: cmake . -DWITH_UNIT_TESTS=True -DWITH_PLUGIN_GDALMODULE=TRUE && make
